### ISSUE TITLE
Invalid query param signature when signature validation is enabled

### ISSUE THREAD

**Issue by nicolabeghin** [lscorcia/keycloak-spid-provider#16]
Going through the [spid-saml-check](https://github.com/italia/spid-saml-check) hell.. Don't know if it's an issue with the tool itself or what, but Keycloak is rejecting the response (this is the Keycloak's generated SPID SP [metadata.xml.zip](https://github.com/lscorcia/keycloak-spid-provider/files/6135783/metadata.xml.zip)). Could it be because the 1st IdP certificate is used in place of the requested one?
> org.keycloak.common.VerificationException: org.keycloak.common.VerificationException: Invalid query param signature

    ERROR [org.keycloak.broker.spid.SpidSAMLEndpoint] (default task-100) validation failed: org.keycloak.common.VerificationException: org.keycloak.common.VerificationException: Invalid query param signature
    at org.keycloak.keycloak-services@12.0.4//org.keycloak.protocol.saml.SamlProtocolUtils.verifyRedirectSignature(SamlProtocolUtils.java:169)
    at org.keycloak.keycloak-services@12.0.4//org.keycloak.protocol.saml.SamlProtocolUtils.verifyRedirectSignature(SamlProtocolUtils.java:127)
    at deployment.spid-provider.jar//org.keycloak.broker.spid.SpidSAMLEndpoint$RedirectBinding.verifySignature(SpidSAMLEndpoint.java:645)
    at deployment.spid-provider.jar//org.keycloak.broker.spid.SpidSAMLEndpoint$Binding.handleSamlResponse(SpidSAMLEndpoint.java:548)
    at deployment.spid-provider.jar//org.keycloak.broker.spid.SpidSAMLEndpoint$Binding.execute(SpidSAMLEndpoint.java:250)
    at deployment.spid-provider.jar//org.keycloak.broker.spid.SpidSAMLEndpoint.redirectBinding(SpidSAMLEndpoint.java:154)

Issue happens only if `Validate signature` is enabled as per [wiki](https://github.com/lscorcia/keycloak-spid-provider/wiki/Defining-SPID-IdPs)
![image](https://user-images.githubusercontent.com/2743637/111044059-94906400-8446-11eb-894c-8faada12f7e0.png)

Tests performed:
1. it doesn't happen when the flag is disabled on the 1st SPID provider (not the required one)
2. **it does happen if the flag is enabled on the 1st SPID provider and disabled in the required one** => seems like it's not honored on the provider-specific SPID settings

Deployed `spid-saml-check` instance metadata: https://www.spid-validator.it/metadata.xml

![image](https://user-images.githubusercontent.com/2743637/111051553-35395080-8454-11eb-85f4-9ee1716e2741.png)

## spid-saml-check response
![image](https://user-images.githubusercontent.com/2743637/111051656-1f785b00-8455-11eb-9898-5ef9ab720688.png)
![image](https://user-images.githubusercontent.com/2743637/111051667-299a5980-8455-11eb-8ccf-b5c8ae3e2c16.png)

**Comment by nicolabeghin** [comment]
similar to #4

**Comment by nicolabeghin** [comment]
By enabling backchannel logout, issue was fixed. Don't understand why, but it's ok! :D 

![image](https://user-images.githubusercontent.com/2743637/111074555-ba1f7b00-84e3-11eb-9369-d63d1345f481.png)
