### ISSUE TITLE
elemento SingleLogoutService per multipli provider

### ISSUE THREAD

**Issue by GermanoGiudici** [lscorcia/keycloak-spid-provider#4]
Ciao,
ho provato a generare i service provider metadata inserendo un solo tag `md:SingleLogoutService`, uno a caso tra quelli disponibili nei singoli metadata degli idp configurati (come descritto nel wiki). Sembra ci sia un problema quando è attivo il controllo della signature lato idp keycloak, come richiesto nei metadata dell'idp scaricati (flag "Validate Signature" nella configurazione dell'idp in keycloak). Immagino sia dovuto al check della signature firmato con un certificato differente.
Anche inserendo gli `md:SingleLogoutService` per tutti gli idp, la situazione non cambia, a meno di disattivare il flag "Validate Signature"
Ti è capitato già questo problema? In allegato il file dei metadata del service provider che sto utilizzando per le prove. 
[spmetadata.xml.zip](https://github.com/lscorcia/keycloak-spid-provider/files/5825987/spmetadata.xml.zip)

**Comment by lscorcia** [comment]
Buongiorno Germano,
mi pareva di aver rimosso dal wiki l'indicazione di avere un solo `SingleLogoutService`, era un mio errore perché in realtà la federazione SPID supporta regolarmente più di un tag di questo tipo.
Per quanto riguarda l'altra segnalazione, in realtà non ho riscontrato questo problema. L'unico dubbio che mi viene in mente è che sulla configurazione dei miei IdP di produzione ho attivato la funzionalità di `Backchannel Logout`, può essere questa la differenza? Con quale IdP hai ottenuto questo errore?

Forse un dump delle richieste SAML potrebbe essere utile per diagnosticare il problema.

PS: Nel tuo metadato gli attributi index dei tag `md:AttributeConsumingService` non sono univoci, immagino siano varie prove ma così com'è non dovrebbe essere valido.

**Comment by GermanoGiudici** [comment]
Ciao Luca e grazie della risposta. Sui metadata c'era un refuso, grazie per avermelo segnalato.
ho configurato tutti gli idp spid recuperando i dati da internet, quindi mi aspetto che i certificati siano validi. Essendo in test non mi posso autenticare da loro, quindi il problema l'ho visto in questo scenario:

mi autentico usando un validator https://spid-saml-check-spide6.okd-entando.org/ (installazione nostra di test) lo configuro passando i metadati che sono qui https://4amyzrjw8z3ny68rl2f3wg-on.drv.tw/web-server/spmetadata-local.xml (sono una versione corretta di quelli che ti ho passato) chiudo il giro facendomi spedire una response, e fino qui tutto ok, risulto autenticato.

Quando vado a fare il logout, arrivo correttamente sul validator che fa fare al browser una redirect sull'edpoint di logout dell'idp NAMIRIA di keycloak (forse perchè è il primo SingleLogoutService del service provider metadata...) 

Questa è la chiamata che tipicamente va in errore, richiesta dal validator
`Request URL: http://kc-local-test:8080/auth/realms/spid/broker/Namirial%20ID/endpoint?SAMLResponse=fVJda9tAEHwP5D8YQR%2FPd5JlfRx2oNQUDGmhcchDX8JKWsVHpDtxuwrJv6%2BkWKnTgvdxd2ZuZrgNQdt0%2BtY9uZ7vkDpnCRfXV4thXtvGkp4A26D3VjsgQ9pCi6S51IevP251tFS6845d6ZrgP%2BJlHhChZ%2BPsTNzvtsFjDutVgXklirheizjJUUCMiVhhXIVZFNcKqpnwgJ4G%2FjYY5D5EiHrcW2KwPBxUFAoVijC9D1O9znSU%2FZ6ROyQ2FnhSODJ3WsrnUjSuhEbwcNSZypSEno%2FSIzQtSepMJQvvntHLn9Aab6D5Eqn9TqKtOmcsBycXdm7z3m2D%2Fe4R0iJRWVGIJF%2FFIl7lqYBCoVBYYwFpnoQFBjfv5M3YnZ6C%2BJPXcb473wJf7nTcmErUE1SjZcNvwV%2BJwTP%2B6qExtUH%2FHpqG1C%2FDpgJ2fjkGXD65l6Xh2c04p3amao7u1MxGnvmcwGf2O31g4J7ORD7tv7kKFw%2FQ9Hg5EE1ofejLEokCOVck%2F3nk%2Bmpeff7MN38A&RelayState=bbeeacd0-1fc7-4ff8-a3b4-d9a8aae4847d&SigAlg=http%3A%2F%2Fwww.w3.org%2F2001%2F04%2Fxmldsig-more%23rsa-sha256&Signature=Hu%2B%2Fagk4WvIsKJ7KFbVZc794VRMLs3vUFGliE2NiuDdIChUwYXbsA97Uel0KEc21gNo3LT%2BgLZVY6WuYZJv8a56pHnTe4L36jXZtPfVBGxxsh8%2FZNkzTrTFm1fD6t%2BhokxSEDC5hbZlxxCbF7hE4Ey77vHnDEgqLm5ibpZem4o4eF00uM4%2FmPlB%2Bb%2BiIVdCwmiJeMEeR7uwHEYxL5m%2BNve7YZM%2F7l02RQZgKaPdDN3byr3YPcB5ler5jLB7XRXOJwLTS2UXXJNtWCAjOrQCWxwjKbY7kz%2FrdqlOaNDzXorDxEm1S7XkTt0Z8TT1HSjsYrdEWfnl6EowAtrK93j38%2BA%3D%3D
Request Method: GET
Status Code: 302 Found
Remote Address: 127.0.0.1:8080
Referrer Policy: no-referrer
Connection: keep-alive
Content-Length: 0
Date: Sun, 17 Jan 2021 17:58:28 GMT
Location: http://kc-local-test:8081/keycloak-client-test.html
Referrer-Policy: no-referrer
Set-Cookie: KEYCLOAK_IDENTITY=; Version=1; Comment=Expiring cookie; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Max-Age=0; Path=/auth/realms/spid/; HttpOnly
Set-Cookie: KEYCLOAK_IDENTITY_LEGACY=; Version=1; Comment=Expiring cookie; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Max-Age=0; Path=/auth/realms/spid/; HttpOnly
Set-Cookie: KEYCLOAK_SESSION=; Version=1; Comment=Expiring cookie; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Max-Age=0; Path=/auth/realms/spid/
Set-Cookie: KEYCLOAK_SESSION_LEGACY=; Version=1; Comment=Expiring cookie; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Max-Age=0; Path=/auth/realms/spid/
Set-Cookie: KEYCLOAK_IDENTITY=; Version=1; Comment=Expiring cookie; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Max-Age=0; Path=/auth/realms/spid; HttpOnly
Set-Cookie: KEYCLOAK_IDENTITY_LEGACY=; Version=1; Comment=Expiring cookie; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Max-Age=0; Path=/auth/realms/spid; HttpOnly
Set-Cookie: KEYCLOAK_SESSION=; Version=1; Comment=Expiring cookie; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Max-Age=0; Path=/auth/realms/spid
Set-Cookie: KEYCLOAK_SESSION_LEGACY=; Version=1; Comment=Expiring cookie; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Max-Age=0; Path=/auth/realms/spid
Set-Cookie: KEYCLOAK_REMEMBER_ME=; Version=1; Comment=Expiring cookie; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Max-Age=0; Path=/auth/realms/spid/; HttpOnly
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9,it-IT;q=0.8,it;q=0.7
Cache-Control: no-cache
Connection: keep-alive
Cookie: AUTH_SESSION_ID_LEGACY=bbeeacd0-1fc7-4ff8-a3b4-d9a8aae4847d.germanos-macbook-pro; KEYCLOAK_IDENTITY_LEGACY=eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJlYWMwNGVjZC1hMzYwLTRhZjUtYmIyMi1mMTA5MGY3NGZhY2EifQ.eyJleHAiOjE2MTA5NDIyOTksImlhdCI6MTYxMDkwNjI5OSwianRpIjoiYzNiNTg4ODEtZDJjNy00NjU2LWJjOTMtOGIwODU5NDk3YjkxIiwiaXNzIjoiaHR0cDovL2tjLWxvY2FsLXRlc3Q6ODA4MC9hdXRoL3JlYWxtcy9zcGlkIiwic3ViIjoiZmEwZTdiYmQtOWM4ZS00YjA3LWEwYTMtZGE4MTZmNGUwZTg3IiwidHlwIjoiU2VyaWFsaXplZC1JRCIsInNlc3Npb25fc3RhdGUiOiJiYmVlYWNkMC0xZmM3LTRmZjgtYTNiNC1kOWE4YWFlNDg0N2QiLCJzdGF0ZV9jaGVja2VyIjoieTJFMHQ3NEJWUjFscmprbzZZeHRrWWtwODEyWFlkSEs1TEw0bzRWNm5zMCJ9.3BGB-xFsvCI1fvSSqvcK2DvC-UhB5fIe4-EwOIHL3_w; KEYCLOAK_SESSION_LEGACY=spid/fa0e7bbd-9c8e-4b07-a0a3-da816f4e0e87/bbeeacd0-1fc7-4ff8-a3b4-d9a8aae4847d
Host: kc-local-test:8080
Pragma: no-cache
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
SAMLResponse: fVJda9tAEHwP5D8YQR/Pd5JlfRx2oNQUDGmhcchDX8JKWsVHpDtxuwrJv6+kWKnTgvdxd2ZuZrgNQdt0+tY9uZ7vkDpnCRfXV4thXtvGkp4A26D3VjsgQ9pCi6S51IevP251tFS6845d6ZrgP+JlHhChZ+PsTNzvtsFjDutVgXklirheizjJUUCMiVhhXIVZFNcKqpnwgJ4G/jYY5D5EiHrcW2KwPBxUFAoVijC9D1O9znSU/Z6ROyQ2FnhSODJ3WsrnUjSuhEbwcNSZypSEno/SIzQtSepMJQvvntHLn9Aab6D5Eqn9TqKtOmcsBycXdm7z3m2D/e4R0iJRWVGIJF/FIl7lqYBCoVBYYwFpnoQFBjfv5M3YnZ6C+JPXcb473wJf7nTcmErUE1SjZcNvwV+JwTP+6qExtUH/HpqG1C/DpgJ2fjkGXD65l6Xh2c04p3amao7u1MxGnvmcwGf2O31g4J7ORD7tv7kKFw/Q9Hg5EE1ofejLEokCOVck/3nk+mpeff7MN38A
RelayState: bbeeacd0-1fc7-4ff8-a3b4-d9a8aae4847d
SigAlg: http://www.w3.org/2001/04/xmldsig-more#rsa-sha256
Signature: Hu+/agk4WvIsKJ7KFbVZc794VRMLs3vUFGliE2NiuDdIChUwYXbsA97Uel0KEc21gNo3LT+gLZVY6WuYZJv8a56pHnTe4L36jXZtPfVBGxxsh8/ZNkzTrTFm1fD6t+hokxSEDC5hbZlxxCbF7hE4Ey77vHnDEgqLm5ibpZem4o4eF00uM4/mPlB+b+iIVdCwmiJeMEeR7uwHEYxL5m+Nve7YZM/7l02RQZgKaPdDN3byr3YPcB5ler5jLB7XRXOJwLTS2UXXJNtWCAjOrQCWxwjKbY7kz/rdqlOaNDzXorDxEm1S7XkTt0Z8TT1HSjsYrdEWfnl6EowAtrK93j38+A==`

a questo punto il giro va in errore per validazione del parametro in request:

`18:30:46,997 ERROR [org.keycloak.broker.spid.SpidSAMLEndpoint] (default task-172) validation failed: org.keycloak.common.VerificationException: org.keycloak.common.VerificationException: Invalid query param signature
	at org.keycloak.keycloak-services@12.0.1//org.keycloak.protocol.saml.SamlProtocolUtils.verifyRedirectSignature(SamlProtocolUtils.java:169)
	at org.keycloak.keycloak-services@12.0.1//org.keycloak.protocol.saml.SamlProtocolUtils.verifyRedirectSignature(SamlProtocolUtils.java:127)
	at deployment.spid-provider.jar//org.keycloak.broker.spid.SpidSAMLEndpoint$RedirectBinding.verifySignature(SpidSAMLEndpoint.java:637)
	at deployment.spid-provider.jar//org.keycloak.broker.spid.SpidSAMLEndpoint$Binding.handleSamlResponse(SpidSAMLEndpoint.java:540)
	at deployment.spid-provider.jar//org.keycloak.broker.spid.SpidSAMLEndpoint$Binding.execute(SpidSAMLEndpoint.java:253)
	at deployment.spid-provider.jar//org.keycloak.broker.spid.SpidSAMLEndpoint.redirectBinding(SpidSAMLEndpoint.java:157)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
`

Riesco a risolvere se:
disabilito il flag di validate signature su NAMIRIAL o copio il certificato con cui ha firmato il validator nell'idp NAMIRIAL.

Da questa analisi sembra che tramite la configurazione dei miei metadata, in particolare il SingleLogoutService, l'idp (in questo caso il validator) giri il logout sul primo SingleLogoutService che incontra, ma il messaggio viene firmato e quindi nel caso in cui la validazione sia attiva con un certificato diverso, il giro non si chiude.

Se così fosse, esiste che tu sappia un modo nei metadata del service provider per agganciare l'url di logout a un qualcosa che identifichi l'idp?

In allegato la traccia saml della logout (saml chrome panel)
[SAMLChromeExport-namirial-logout-error.json.zip](https://github.com/lscorcia/keycloak-spid-provider/files/5826577/SAMLChromeExport-namirial-logout-error.json.zip)

**Comment by lscorcia** [comment]
Ciao @erapsag , all'epoca anche io ho verificato lo stesso comportamento segnalato da parte di spid-testenv2, ma non ho dedicato più di tanto tempo alla diagnosi perché i test con spid-saml-check rispecchiano meglio quanto avviene effettivamente in produzione. Lascio la issue aperta perché cercherò di guardarci, ma sicuramente è prioritaria l'altra tua segnalazione.

**Comment by nicolabeghin** [comment]
Chiudo in quanto vecchio di 3 anni
